clear;clc;
imread("C:\Users\OS\OneDrive\Documentos\ImageProcessing\anh1.jpg";
"C:\Users\OS\OneDrive\Documentos\ImageProcessing\anh2.jpg";
"C:\Users\OS\OneDrive\Documentos\ImageProcessing\anh3.jpg";
"C:\Users\OS\OneDrive\Documentos\ImageProcessing\anh4.jpg";
"C:\Users\OS\OneDrive\Documentos\ImageProcessing\anh5.jpg";
"C:\Users\OS\OneDrive\Documentos\ImageProcessing\anh7.jpg";
"C:\Users\OS\OneDrive\Documentos\ImageProcessing\anh8.jpg";
"C:\Users\OS\OneDrive\Documentos\ImageProcessing\anh9.jpg";
"C:\Users\OS\OneDrive\Documentos\ImageProcessing\anh10.jpg";
"C:\Users\OS\OneDrive\Documentos\ImageProcessing\anh11.jpg";
"C:\Users\OS\OneDrive\Documentos\ImageProcessing\anh12.jpg";
"C:\Users\OS\OneDrive\Documentos\ImageProcessing\anh13.jpg";
"C:\Users\OS\OneDrive\Documentos\ImageProcessing\anh14.jpg";
"C:\Users\OS\OneDrive\Documentos\ImageProcessing\anh15.jpg";
"C:\Users\OS\OneDrive\Documentos\ImageProcessing\anh16.jpg")